import { PrismaClient } from '../app/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import 'dotenv/config'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  // ─── Company 1: Clínica Dental Perú — medium opportunity ──────────────────
  const dental = await prisma.company.create({
    data: {
      name: 'Clínica Dental San Marcos',
      industry: 'Dental / Odontología',
      country: 'peru',
      city: 'Lima',
      website: 'https://dentalsanmarcos.pe',
      whatsapp: '+51987654321',
      instagram: null,
      linkedin: null,
      googleBusinessUrl: null,
      status: 'active',
      leadSource: 'google_maps',
      latestOpportunityScore: 62,
      latestPriorityLevel: 'high',
      latestEvaluatedAt: new Date('2026-06-05T10:00:00Z'),
    },
  })

  await prisma.evaluation.create({
    data: {
      companyId: dental.id,
      evaluatedBy: 'alejandro@kronosdata.tech',
      signalHasWebsite: true,
      signalHasWhatsapp: true,
      signalHasContactForm: false,
      signalHasBookingSystem: false,
      signalHasInstagram: false,
      signalHasLinkedin: false,
      signalHasGoogleBusiness: false,
      signalHasReviews: true,
      signalHasUnansweredReviews: true,
      signalHasClearCta: false,
      signalHasLeadCapture: false,
      signalSlowResponse: true,
      signalWeakFollowup: true,
      signalManualWork: true,
      signalWeakOnlinePresence: true,
      scoreLeadGeneration: 75,
      scoreFollowUp: 100,
      scoreConversionProcess: 100,
      scoreAutomationOpportunity: 100,
      scoreOnlinePresence: 50,
      scoreReputation: 60,
      opportunityScore: 62,
      priorityLevel: 'high',
      detectedProblems: [
        'Sin formulario de contacto',
        'Sin sistema de reservas o citas',
        'Sin presencia en Instagram',
        'Sin presencia en LinkedIn',
        'Sin Google Business Profile',
        'Reseñas sin responder detectadas',
        'Sin llamada a la acción (CTA) clara',
        'Sin captura de leads en el sitio',
        'Señales de respuesta lenta a consultas',
        'Señales de seguimiento débil después del primer contacto',
        'Señales de trabajo manual repetitivo en procesos',
        'Presencia online débil o desactualizada',
      ],
      probablePainPoint: 'Fuga masiva de ingresos: sin captura de leads, sin seguimiento y procesos 100% manuales.',
      recommendedSolution: 'Automatización de WhatsApp con respuestas inmediatas + sistema de reservas y citas online.',
      estimatedValueMin: 1200,
      estimatedValueMax: 2625,
      estimatedLeadsLostPerMonth: 60,
      estimatedRevenueLostPerMonth: 600,
      estimatedRoiPotential: 6,
      recommendedServices: ['Automatización de WhatsApp', 'Sistema de Reservas y Citas', 'Funnel de Captura de Leads', 'CRM y Automatización de Seguimiento', 'Configuración de Google Business', 'Gestión de Reseñas', 'Auditoría de Presencia Digital'],
      implementationDifficulty: 'medium',
      implementationTimeEstimate: '3–6 semanas',
      estimatedProjectPriceMin: 4400,
      estimatedProjectPriceMax: 9900,
      evaluatedAt: new Date('2026-06-05T10:00:00Z'),
    },
  })

  await prisma.salesNote.create({
    data: {
      companyId: dental.id,
      contactName: 'Dr. Carlos Mendez',
      contactRole: 'Director',
      contactPhone: '+51987654321',
      contactEmail: 'cmendez@dentalsanmarcos.pe',
      contactStatus: 'contacted',
      meetingStatus: 'scheduled',
      meetingDate: new Date('2026-06-15T14:00:00Z'),
      meetingNotes: 'Interesado en automatización. Hablar de sistema de citas primero.',
      budgetMin: 800,
      budgetMax: 2500,
      budgetCurrency: 'USD',
      objections: 'Cree que sus pacientes no usan sistemas digitales',
      followUpNotes: 'Enviar caso de estudio de otra clínica dental en Lima',
      nextAction: 'Enviar propuesta',
      nextActionDate: new Date('2026-06-16T09:00:00Z'),
      assignedTo: 'alejandro@kronosdata.tech',
      closeProbability: 65,
    },
  })

  await prisma.outreachHistory.create({
    data: {
      companyId: dental.id,
      channel: 'whatsapp',
      messageSent: 'Hola Dr. Mendez, le escribo de Kronos Data. Notamos que su clínica podría estar perdiendo pacientes por falta de sistema de reservas online...',
      sentBy: 'alejandro@kronosdata.tech',
      sentAt: new Date('2026-06-03T10:30:00Z'),
      responseReceived: true,
      responseType: 'interested',
      responseNotes: 'Respondió el mismo día. Quiere saber más.',
      repliedAt: new Date('2026-06-03T14:00:00Z'),
      nextFollowUpAt: new Date('2026-06-15T14:00:00Z'),
      sequenceNumber: 1,
      channelAccount: '+51987654321',
      isAutomated: false,
    },
  })

  // ─── Company 2: Inmobiliaria Lima Capital — hot opportunity ────────────────
  const realestate = await prisma.company.create({
    data: {
      name: 'Lima Capital Propiedades',
      industry: 'Inmobiliaria / Real Estate',
      country: 'peru',
      city: 'Lima',
      website: null,
      whatsapp: '+51976543210',
      instagram: null,
      linkedin: null,
      googleBusinessUrl: null,
      status: 'active',
      leadSource: 'linkedin',
      latestOpportunityScore: 87,
      latestPriorityLevel: 'hot',
      latestEvaluatedAt: new Date('2026-06-08T09:00:00Z'),
    },
  })

  await prisma.evaluation.create({
    data: {
      companyId: realestate.id,
      evaluatedBy: 'alejandro@kronosdata.tech',
      signalHasWebsite: false,
      signalHasWhatsapp: true,
      signalHasContactForm: false,
      signalHasBookingSystem: false,
      signalHasInstagram: false,
      signalHasLinkedin: false,
      signalHasGoogleBusiness: false,
      signalHasReviews: false,
      signalHasUnansweredReviews: false,
      signalHasClearCta: false,
      signalHasLeadCapture: false,
      signalSlowResponse: true,
      signalWeakFollowup: true,
      signalManualWork: true,
      signalWeakOnlinePresence: true,
      scoreLeadGeneration: 100,
      scoreFollowUp: 100,
      scoreConversionProcess: 100,
      scoreAutomationOpportunity: 100,
      scoreOnlinePresence: 100,
      scoreReputation: 70,
      opportunityScore: 87,
      priorityLevel: 'hot',
      detectedProblems: [
        'Sin sitio web activo',
        'Sin formulario de contacto',
        'Sin sistema de reservas o citas',
        'Sin presencia en Instagram',
        'Sin presencia en LinkedIn',
        'Sin Google Business Profile',
        'Sin reseñas en Google',
        'Sin llamada a la acción (CTA) clara',
        'Sin captura de leads en el sitio',
        'Señales de respuesta lenta a consultas',
        'Señales de seguimiento débil después del primer contacto',
        'Señales de trabajo manual repetitivo en procesos',
        'Presencia online débil o desactualizada',
      ],
      probablePainPoint: 'Fuga masiva de ingresos: sin captura de leads, sin seguimiento y procesos 100% manuales. El negocio está perdiendo clientes en cada etapa del proceso de venta.',
      recommendedSolution: 'Automatización de WhatsApp con respuestas inmediatas + funnel de captura de leads con CTA optimizado.',
      estimatedValueMin: 1800,
      estimatedValueMax: 5000,
      estimatedLeadsLostPerMonth: 32,
      estimatedRevenueLostPerMonth: 4800,
      estimatedRoiPotential: 32,
      recommendedServices: ['Automatización de WhatsApp', 'Sistema de Reservas y Citas', 'Funnel de Captura de Leads', 'CRM y Automatización de Seguimiento', 'Configuración de Google Business', 'Paquete de Presencia en Redes Sociales', 'Desarrollo de Sitio Web', 'Automatización del Proceso de Ventas', 'Auditoría de Presencia Digital'],
      implementationDifficulty: 'high',
      implementationTimeEstimate: '6–12 semanas',
      estimatedProjectPriceMin: 9400,
      estimatedProjectPriceMax: 22100,
      evaluatedAt: new Date('2026-06-08T09:00:00Z'),
    },
  })

  await prisma.salesNote.create({
    data: {
      companyId: realestate.id,
      contactName: 'Rosa Villanueva',
      contactRole: 'Gerente General',
      contactPhone: '+51976543210',
      contactEmail: null,
      contactStatus: 'attempted',
      meetingStatus: 'not_scheduled',
      meetingNotes: null,
      objections: null,
      nextAction: 'Segundo intento de contacto por LinkedIn',
      nextActionDate: new Date('2026-06-12T10:00:00Z'),
      assignedTo: 'alejandro@kronosdata.tech',
      closeProbability: 40,
    },
  })

  await prisma.outreachHistory.create({
    data: {
      companyId: realestate.id,
      channel: 'linkedin',
      messageSent: 'Hola Rosa, vi tu perfil en LinkedIn. En Kronos Data ayudamos a inmobiliarias en Lima a generar leads qualificados con automatización...',
      sentBy: 'alejandro@kronosdata.tech',
      sentAt: new Date('2026-06-08T11:00:00Z'),
      responseReceived: false,
      responseType: 'no_response',
      nextFollowUpAt: new Date('2026-06-12T10:00:00Z'),
      sequenceNumber: 1,
      channelAccount: 'linkedin.com/in/alejandro',
      isAutomated: false,
    },
  })

  // ─── Company 3: Estudio Jurídico Andino — high opportunity ────────────────
  const lawfirm = await prisma.company.create({
    data: {
      name: 'Estudio Jurídico Andino',
      industry: 'Estudio Jurídico / Law Firm',
      country: 'colombia',
      city: 'Bogotá',
      website: 'https://juridicoandinoco.com',
      whatsapp: null,
      instagram: null,
      linkedin: 'https://linkedin.com/company/juridico-andino',
      googleBusinessUrl: 'https://g.page/juridicoandinoco',
      status: 'active',
      leadSource: 'referral',
      latestOpportunityScore: 71,
      latestPriorityLevel: 'high',
      latestEvaluatedAt: new Date('2026-06-09T11:00:00Z'),
    },
  })

  await prisma.evaluation.create({
    data: {
      companyId: lawfirm.id,
      evaluatedBy: 'alejandro@kronosdata.tech',
      signalHasWebsite: true,
      signalHasWhatsapp: false,
      signalHasContactForm: true,
      signalHasBookingSystem: false,
      signalHasInstagram: false,
      signalHasLinkedin: true,
      signalHasGoogleBusiness: true,
      signalHasReviews: true,
      signalHasUnansweredReviews: false,
      signalHasClearCta: false,
      signalHasLeadCapture: false,
      signalSlowResponse: true,
      signalWeakFollowup: true,
      signalManualWork: true,
      signalWeakOnlinePresence: false,
      scoreLeadGeneration: 60,
      scoreFollowUp: 100,
      scoreConversionProcess: 100,
      scoreAutomationOpportunity: 100,
      scoreOnlinePresence: 50,
      scoreReputation: 0,
      opportunityScore: 71,
      priorityLevel: 'high',
      detectedProblems: [
        'Sin WhatsApp visible',
        'Sin sistema de reservas o citas',
        'Sin presencia en Instagram',
        'Sin llamada a la acción (CTA) clara',
        'Sin captura de leads en el sitio',
        'Señales de respuesta lenta a consultas',
        'Señales de seguimiento débil después del primer contacto',
        'Señales de trabajo manual repetitivo en procesos',
      ],
      probablePainPoint: 'Fuga masiva de ingresos: sin captura de leads, sin seguimiento y procesos 100% manuales.',
      recommendedSolution: 'Automatización de WhatsApp con respuestas inmediatas + sistema de reservas y citas online.',
      estimatedValueMin: 2000,
      estimatedValueMax: 4125,
      estimatedLeadsLostPerMonth: 20,
      estimatedRevenueLostPerMonth: 1500,
      estimatedRoiPotential: 9,
      recommendedServices: ['Automatización de WhatsApp', 'Sistema de Reservas y Citas', 'Funnel de Captura de Leads', 'CRM y Automatización de Seguimiento', 'Automatización del Proceso de Ventas'],
      implementationDifficulty: 'high',
      implementationTimeEstimate: '6–12 semanas',
      estimatedProjectPriceMin: 7000,
      estimatedProjectPriceMax: 13800,
      evaluatedAt: new Date('2026-06-09T11:00:00Z'),
    },
  })

  await prisma.salesNote.create({
    data: {
      companyId: lawfirm.id,
      contactName: 'Lic. Andrés Morales',
      contactRole: 'Socio Principal',
      contactPhone: null,
      contactEmail: 'amorales@juridicoandinoco.com',
      contactStatus: 'in_conversation',
      meetingStatus: 'scheduled',
      meetingDate: new Date('2026-06-18T16:00:00Z'),
      meetingNotes: 'Demo de sistema de agendamiento de consultas online.',
      budgetMin: 1500,
      budgetMax: 5000,
      budgetCurrency: 'USD',
      objections: 'Clientes son tradicionales, dudan de automatización',
      followUpNotes: 'Énfasis en que el sistema puede parecer manual al cliente final',
      nextAction: 'Preparar demo personalizada',
      nextActionDate: new Date('2026-06-16T10:00:00Z'),
      assignedTo: 'alejandro@kronosdata.tech',
      closeProbability: 55,
    },
  })

  await prisma.outreachHistory.create({
    data: {
      companyId: lawfirm.id,
      channel: 'email',
      messageSent: 'Estimado Lic. Morales, le escribo desde Kronos Data. Identificamos que su estudio podría automatizar la captación y agenda de consultas iniciales...',
      sentBy: 'alejandro@kronosdata.tech',
      sentAt: new Date('2026-06-06T09:00:00Z'),
      responseReceived: true,
      responseType: 'asked_to_follow_up',
      responseNotes: 'Respondió al día siguiente. Quiere demo la semana del 16.',
      repliedAt: new Date('2026-06-07T08:30:00Z'),
      nextFollowUpAt: new Date('2026-06-16T10:00:00Z'),
      sequenceNumber: 1,
      channelAccount: 'alejandro@kronosdata.tech',
      isAutomated: false,
    },
  })

  // ─── Company 4: Restaurante El Mirador — high opportunity ─────────────────
  const restaurant = await prisma.company.create({
    data: {
      name: 'Restaurante El Mirador',
      industry: 'Restaurante / Food & Beverage',
      country: 'peru',
      city: 'Cusco',
      website: 'https://elmiradorrest.pe',
      whatsapp: '+51964321098',
      instagram: 'https://instagram.com/elmiradorrest',
      linkedin: null,
      googleBusinessUrl: 'https://g.page/elmiradorrest',
      status: 'contacted',
      leadSource: 'google_maps',
      latestOpportunityScore: 68,
      latestPriorityLevel: 'high',
      latestEvaluatedAt: new Date('2026-06-07T15:00:00Z'),
    },
  })

  await prisma.evaluation.create({
    data: {
      companyId: restaurant.id,
      evaluatedBy: 'alejandro@kronosdata.tech',
      signalHasWebsite: true,
      signalHasWhatsapp: true,
      signalHasContactForm: false,
      signalHasBookingSystem: false,
      signalHasInstagram: true,
      signalHasLinkedin: false,
      signalHasGoogleBusiness: true,
      signalHasReviews: true,
      signalHasUnansweredReviews: true,
      signalHasClearCta: false,
      signalHasLeadCapture: false,
      signalSlowResponse: true,
      signalWeakFollowup: false,
      signalManualWork: true,
      signalWeakOnlinePresence: false,
      scoreLeadGeneration: 50,
      scoreFollowUp: 50,
      scoreConversionProcess: 100,
      scoreAutomationOpportunity: 100,
      scoreOnlinePresence: 20,
      scoreReputation: 30,
      opportunityScore: 68,
      priorityLevel: 'high',
      detectedProblems: [
        'Sin formulario de contacto',
        'Sin sistema de reservas o citas',
        'Sin presencia en LinkedIn',
        'Reseñas sin responder detectadas',
        'Sin llamada a la acción (CTA) clara',
        'Sin captura de leads en el sitio',
        'Señales de respuesta lenta a consultas',
        'Señales de trabajo manual repetitivo en procesos',
      ],
      probablePainPoint: 'Cuello de botella operativo: los procesos manuales consumen tiempo del equipo e impiden dar respuesta y seguimiento rápido.',
      recommendedSolution: 'Sistema de reservas y citas online para eliminar gestión manual + automatización de WhatsApp con respuestas inmediatas.',
      estimatedValueMin: 1200,
      estimatedValueMax: 1750,
      estimatedLeadsLostPerMonth: 25,
      estimatedRevenueLostPerMonth: 625,
      estimatedRoiPotential: 4,
      recommendedServices: ['Automatización de WhatsApp', 'Sistema de Reservas y Citas', 'Funnel de Captura de Leads', 'Gestión de Reseñas', 'Automatización del Proceso de Ventas', 'Auditoría de Presencia Digital'],
      implementationDifficulty: 'high',
      implementationTimeEstimate: '6–12 semanas',
      estimatedProjectPriceMin: 5200,
      estimatedProjectPriceMax: 12700,
      evaluatedAt: new Date('2026-06-07T15:00:00Z'),
    },
  })

  await prisma.salesNote.create({
    data: {
      companyId: restaurant.id,
      contactName: 'María Quispe',
      contactRole: 'Administradora',
      contactPhone: '+51964321098',
      contactEmail: null,
      contactStatus: 'contacted',
      meetingStatus: 'not_scheduled',
      meetingNotes: null,
      budgetMin: 500,
      budgetMax: 1500,
      budgetCurrency: 'USD',
      objections: 'Presupuesto ajustado por temporada baja',
      followUpNotes: 'Contactar en julio cuando empiece temporada alta',
      nextAction: 'Follow-up en julio',
      nextActionDate: new Date('2026-07-05T10:00:00Z'),
      assignedTo: 'alejandro@kronosdata.tech',
      closeProbability: 35,
    },
  })

  await prisma.outreachHistory.create({
    data: {
      companyId: restaurant.id,
      channel: 'whatsapp',
      messageSent: 'Hola María, le escribo de Kronos Data. Su restaurante tiene muy buenas reseñas en Google, pero notamos que las reservas aún se hacen por llamada...',
      sentBy: 'alejandro@kronosdata.tech',
      sentAt: new Date('2026-06-07T16:00:00Z'),
      responseReceived: true,
      responseType: 'asked_to_follow_up',
      responseNotes: 'Interesada pero dice que julio es mejor momento. Presupuesto limitado ahora.',
      repliedAt: new Date('2026-06-07T18:30:00Z'),
      nextFollowUpAt: new Date('2026-07-05T10:00:00Z'),
      sequenceNumber: 1,
      channelAccount: '+51964321098',
      isAutomated: false,
    },
  })

  // ─── Company 5: Consultora Digital Nexo — medium opportunity ──────────────
  const consultora = await prisma.company.create({
    data: {
      name: 'Consultora Digital Nexo',
      industry: 'Consultoría',
      country: 'peru',
      city: 'Lima',
      website: 'https://nexoconsultora.pe',
      whatsapp: '+51998765432',
      instagram: 'https://instagram.com/nexoconsultora',
      linkedin: 'https://linkedin.com/company/nexo-consultora',
      googleBusinessUrl: null,
      status: 'active',
      leadSource: 'cold_outreach',
      latestOpportunityScore: 46,
      latestPriorityLevel: 'medium',
      latestEvaluatedAt: new Date('2026-06-09T14:00:00Z'),
    },
  })

  await prisma.evaluation.create({
    data: {
      companyId: consultora.id,
      evaluatedBy: 'alejandro@kronosdata.tech',
      signalHasWebsite: true,
      signalHasWhatsapp: true,
      signalHasContactForm: true,
      signalHasBookingSystem: false,
      signalHasInstagram: true,
      signalHasLinkedin: true,
      signalHasGoogleBusiness: false,
      signalHasReviews: false,
      signalHasUnansweredReviews: false,
      signalHasClearCta: true,
      signalHasLeadCapture: false,
      signalSlowResponse: false,
      signalWeakFollowup: true,
      signalManualWork: false,
      signalWeakOnlinePresence: false,
      scoreLeadGeneration: 25,
      scoreFollowUp: 50,
      scoreConversionProcess: 45,
      scoreAutomationOpportunity: 40,
      scoreOnlinePresence: 20,
      scoreReputation: 70,
      opportunityScore: 46,
      priorityLevel: 'medium',
      detectedProblems: [
        'Sin sistema de reservas o citas',
        'Sin Google Business Profile',
        'Sin reseñas en Google',
        'Sin captura de leads en el sitio',
        'Señales de seguimiento débil después del primer contacto',
      ],
      probablePainPoint: 'Pérdida de clientes por tiempo de respuesta: los prospectos contactan, pero la falta de seguimiento los empuja a la competencia.',
      recommendedSolution: 'CRM y automatización de seguimiento + sistema de reservas y citas online.',
      estimatedValueMin: 1200,
      estimatedValueMax: 875,
      estimatedLeadsLostPerMonth: 8,
      estimatedRevenueLostPerMonth: 200,
      estimatedRoiPotential: 2,
      recommendedServices: ['Sistema de Reservas y Citas', 'Funnel de Captura de Leads', 'CRM y Automatización de Seguimiento', 'Configuración de Google Business', 'Auditoría de Presencia Digital'],
      implementationDifficulty: 'medium',
      implementationTimeEstimate: '3–6 semanas',
      estimatedProjectPriceMin: 3800,
      estimatedProjectPriceMax: 7400,
      evaluatedAt: new Date('2026-06-09T14:00:00Z'),
    },
  })

  await prisma.salesNote.create({
    data: {
      companyId: consultora.id,
      contactName: 'Jorge Hidalgo',
      contactRole: 'CEO',
      contactPhone: '+51998765432',
      contactEmail: 'jhidalgo@nexoconsultora.pe',
      contactStatus: 'proposal_sent',
      meetingStatus: 'completed',
      meetingDate: new Date('2026-06-04T11:00:00Z'),
      meetingNotes: 'Reunión de 45 min. Muy receptivo al CRM. Cree que el seguimiento es su mayor problema.',
      budgetMin: 2000,
      budgetMax: 6000,
      budgetCurrency: 'USD',
      objections: 'Quiere que se integre con sus herramientas actuales (Notion + Gmail)',
      salesObservations: 'Perfil técnico. Apreciaría una demo más detallada de la integración.',
      nextAction: 'Esperar respuesta a propuesta enviada el 09/06',
      nextActionDate: new Date('2026-06-14T09:00:00Z'),
      assignedTo: 'alejandro@kronosdata.tech',
      closeProbability: 60,
    },
  })

  await prisma.outreachHistory.create({
    data: {
      companyId: consultora.id,
      channel: 'linkedin',
      messageSent: 'Hola Jorge, vi tu contenido sobre procesos en LinkedIn. Tengo una propuesta específica para consultoras que quieren escalar sin contratar más personal...',
      sentBy: 'alejandro@kronosdata.tech',
      sentAt: new Date('2026-06-01T09:00:00Z'),
      responseReceived: true,
      responseType: 'booked_call',
      responseNotes: 'Respondió en 2 horas. Agendó reunión para el 04/06.',
      repliedAt: new Date('2026-06-01T11:00:00Z'),
      nextFollowUpAt: new Date('2026-06-14T09:00:00Z'),
      sequenceNumber: 1,
      channelAccount: 'linkedin.com/in/alejandro',
      isAutomated: false,
    },
  })

  console.log('✓ Seed complete — 5 companies with evaluations, sales notes, and outreach history')
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (err) => {
    console.error(err)
    await prisma.$disconnect()
    process.exit(1)
  })
